/*
 *      Turbo Vision - Version 2.0
 *
 *      Copyright (c) 1994 by Borland International
 *      All Rights Reserved.
 *
 * Modified by Robert H”hne to be used for RHIDE.
Modified by Salvador E. Tropea

 *
 *
 */

#define _TV_VERSION 0x0103

// SET: Internal release number. Used to check the version of the release
// in programs that are very sensitive, like my editor.
#define TV_MAJOR_VERSION  2
#define TV_MIDDLE_VERSION 0
#define TV_MINOR_VERSION  3
#define TV_VERSION "2.0.3"

// That's the file generated by the configure script:
// Compatibility layer
#include <compatlayer.h>
// This file sets some stuff according to the compiler:
#include <tv/tvconfig.h>
// Basic data types used in many places:
#include <tv/ttypes.h>
#include <tv/tvutil.h>
#include <tv/object.h>
#include <tv/point.h>
#include <tv/rect.h>
#include <tv/tkeys.h>
#include <tv/event.h>
#include <tv/parttree.h>
#include <tv/codepage.h>
#include <tv/gkey.h>
#include <tv/tvutil.h>
#include <tv/tvobjs.h>
#include <tv/tobjstrm.h>
#include <tv/drawbuf.h>
#include <tv/objects.h>
#include <tv/validate.h>
#include <tv/system.h>
#include <tv/msgbox.h>
#include <tv/resource.h>
#include <tv/views.h>
#include <tv/dialogs.h>
#include <tv/stddlg.h>
#include <tv/colorsel.h>
#include <tv/menus.h>
#include <tv/textview.h>
#include <tv/indicato.h>
#include <tv/findrepl.h>
#include <tv/app.h>
#include <tv/fileview.h>
#include <tv/fontcoll.h>

// SET: Start of the THelp* classes incorporated in 2.0
#ifdef INCLUDE_HELPBASE_H
 #include <tv/helpbase.h>
#endif

#ifdef INCLUDE_HELP_H
 #include <tv/help.h>
#endif
// SET: End of the THelp* classes

// SET: Start of the TEditor classes re-incorporated in 1.0.4
#include <tv/editors.h>
#include <tv/tvedit.h>
#include <tv/calc.h>
#include <tv/osclipboard.h>
#include <tv/configfile.h>
